### PR TITLE
Add more domains to the nginx config file

### PR DESCRIPTION
**Pull request by T0biii**
- add augsburg.freifunk.net, www.augsburg.freifunk.net
- add muenchen.freifunk.net/augsburg (SSID-URL)
- add www.muenchen.freifunk.net
- add www.münchen.freifunk.net münchen.freifunk.net
- add xn--mnchen-3ya.freifunk.net www.xn--mnchen-3ya.freifunk.net
- Remove CertBot 
- add Domains to SSL Cert

### CODE REVIEW

**Review by awlx — APPROVED** [review]

**Comment by GoliathLabs** [comment]
@T0biii if I remember correctly we also have münchen.freifunk.net as well as the two www subdomains

**Review by GoliathLabs — CHANGES_REQUESTED** [review]
Add www.muenchen.freifunk.net, münchen.freiifunk.net as well as www.muenchen.freifunk.net to the config

**Comment by T0biii** [comment]
what should we do about this part:
https://github.com/freifunkMUC/ffmuc-salt-public/blob/0938f264054eba30dd35e28e40d5b13fec638d43/nginx/domains/ffmuc.net.conf#L128-L191

is it still "managed by Certbot"?

**Comment by awlx** [comment]
@T0biii I think it's obsolete

**Comment by T0biii** [comment]
and Augsburg must be added here as well, i guess?
https://github.com/freifunkMUC/ffmuc-salt-public/blob/0f9bef1a25af2fb5d830460b00601458b877b5ec/certs/init.sls#L95-L113

**Comment by T0biii** [comment]
maybe so? i dont know xD

**Review by awlx — APPROVED** [review]

**Comment by GoliathLabs** [comment]
@awlx shall we merge this?

**Pull request merged**
