### PR TITLE
Remove: Obsolete docker-containers section

### PR DESCRIPTION
**Pull request by GoliathLabs**
I have removed the deprecated Docker container section from this repository. Since we are updating them by hand anyway and the salt-linter is not happy with the configurations, it would be better to remove them instead of keeping an old state like this in the repository

### CODE REVIEW

**Comment by DasSkelett** [comment]
I don't think I can meaningfully review this PR, I have no clue about the Salt setup and what is and what isn't managed through Git or by hand

**Review by krombel — CHANGES_REQUESTED** [review]
diun and speedtest got added later and are current.
Although I am in general welcoming a cleanup I would not remove especially that definitions.

I don't know if we should move each program into its own folder (as I started with those two) or to keep the former approach. But I think it might be better in general to be able to deploy the containers faster in case a docker host fails. So although not beeing deployed automatically (as the rest of the setup is) I would keep the definitions somewhere like in this repo.

**Comment by GoliathLabs** [comment]
> diun and speedtest got added later and are current. Although I am in general welcoming a cleanup I would not remove especially that definitions.
> 
> I don't know if we should move each program into its own folder (as I started with those two) or to keep the former approach. But I think it might be better in general to be able to deploy the containers faster in case a docker host fails. So although not beeing deployed automatically (as the rest of the setup is) I would keep the definitions somewhere like in this repo.

Fair point. I will add both back into the repository in the next few days. However, the other compose files are heavily outdated. We might need to find a better approach than managing Docker via Salt. I'll put that on my ToDo list

**Comment by GoliathLabs** [comment]
@krombel I have now removed the compose files except for the two which are current. I have left the init.sls in the docker-compose root directory for reference. I like your approach with separate folders for each service and would prefer to add our deployments back to the docker-compose directory one by one. The old compose files have already been heavily reworked on the respective docker hosts anyway and no longer match the state in the repository here

**Comment by GoliathLabs** [comment]
Can someone tell me what I did wrong, since black is now also failing?

**Comment by DasSkelett** [comment]
> Can someone tell me what I did wrong, since black is now also failing?

Black 22 has been released a few days ago, which removed support for Python2 source files:
https://github.com/psf/black/blob/main/CHANGES.md#2210

> error: cannot format icinga2/mattermost-notifications.py: Cannot parse: 107:10:     print response
Python 2 support was removed in version 22.0.

**Comment by GoliathLabs** [comment]
And that's why we use tagged versions 🥲Gonna create a PR for this as well...

**Comment by DasSkelett** [comment]
No idea how these scripts are even able to run (awlnx told me the VMs run Ubuntu 20.04 and there shouldn't be any Python2 installed, does Ubuntu do some [2to3](https://docs.python.org/3/library/2to3.html) runtime magic?), but it might make sense to update them.
At least for the mattermost script the [repo](https://github.com/Reamer/icinga2-mattermost) where I think the script was taken from already [did the upgrade](https://github.com/Reamer/icinga2-mattermost/commit/6f80989df419e174991b172759fc7c23af492f70) to Python 3 already, so we could just reimport the script.
But there are more Python (2) files in the [plugins directory](https://github.com/freifunkMUC/ffmuc-salt-public/tree/main/icinga2/plugins) that need updating as well.

**Pull request closed without merging**
